name: Cypress

on:
  deployment_status:

jobs:
  cypress-run:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    env:
      # Triggers loading env vars from .env.test
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          wait-on: ${{ github.event.deployment_status.target_url }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: artifacts-${{ github.run_id }}
          path: |
            ${{ github.workspace }}/cypress/screenshots
            ${{ github.workspace }}/cypress/videos
