name: Run Deployment Tests

on:
  deployment_status:

jobs:
  lighthouse-run:
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-latest
    steps:
      # - name: Dump context
      #   uses: crazy-max/ghaction-dump-context@v1

      - uses: actions/checkout@v3

      - name: Get PR number
        id: pr
        run: |
          number=$(gh pr list --search "${{ github.sha }}" --state open --json number --jq ".[0].number")
          echo "::set-output name=number::$number"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: Static Web App - get preview URL
      #   id: static_web_app_preview_url
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       CUSTOM_DOMAIN='agreeable-rock-039a51810.1.azurestaticapps.net'
      #       LOCATION='centralus'

      #       PREVIEW_URL="https://${CUSTOM_DOMAIN/.[1-9]./-${{github.event.pull_request.number }}.$LOCATION.1.}"

      #       echo "::set-output name=PREVIEW_URL::$PREVIEW_URL"

      # - name: Get preview url
      #   id: preview-url
      #   run: |
      #     DOMAIN='ecommerce-kitchen-sink'

      #     -i3fvqwma3-takeshape.vercel.app
      #   with:
      #     inlineScript: |
      #       CUSTOM_DOMAIN='agreeable-rock-039a51810.1.azurestaticapps.net'
      #       LOCATION='centralus'

      #       PREVIEW_URL="https://${CUSTOM_DOMAIN/.[1-9]./-${{github.event.pull_request.number }}.$LOCATION.1.}"

      #       echo "::set-output name=PREVIEW_URL::$PREVIEW_URL"

      # - name: Static Web App - wait for preview
      #   id: static_web_app_wait_for_preview
      #   uses: nev7n/wait_for_response@v1
      #   with:
      #     url: "${{ steps.static_web_app_preview_url.outputs.PREVIEW_URL }}"
      #     responseCode: 200
      #     timeout: 600000
      #     interval: 1000

      - name: Audit URLs using Lighthouse
        if: steps.pr.outputs.number != ''
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
          configPath: ./.github/workflows/lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 5

      - name: Format lighthouse score
        if: steps.pr.outputs.number != ''
        id: format_lighthouse_score
        uses: actions/github-script@v6
        with:
          script: |
            const lighthouseCommentMaker = require('./.github/workflows/lighthouseCommentMaker.js');

            const lighthouseOutputs = {
              manifest: ${{ steps.lighthouse_audit.outputs.manifest }},
              links: ${{ steps.lighthouse_audit.outputs.links }}
            };

            const comment = lighthouseCommentMaker({ lighthouseOutputs });
            core.setOutput("comment", comment);

      - name: Add Lighthouse stats as comment
        if: steps.pr.outputs.number != ''
        id: comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v2.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.pr.outputs.number }}
          header: lighthouse
          message: ${{ steps.format_lighthouse_score.outputs.comment }}
