name: Test with Jest and Cypress
on: [push]
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install modules
        run: npm ci

      - name: Run typecheck
        run: npm run typecheck

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
        env:
          NEXT_PUBLIC_LOCALE: "en-US"
          NEXT_PUBLIC_AUTH0_DOMAIN: "dev-by9w1mxg.us.auth0.com"
          NEXT_PUBLIC_AUTH0_CLIENT_ID: "qFoQD6d6vGhob9B8lguJbolKKXnL6jDQ"
          NEXT_PUBLIC_AUTH0_REDIRECT_URI: "http://localhost:3000/"
          NEXT_PUBLIC_AUTH0_SCOPE: "openid profile email offline_access"
          NEXT_PUBLIC_AUTH0_AUDIENCE: "https://api.takeshape.io/project/06ccc3dc-a9da-4f5b-9142-5a104db52ee3/auth-0"
          NEXT_PUBLIC_TAKESHAPE_API_URL: "https://api.takeshape.io/project/06ccc3dc-a9da-4f5b-9142-5a104db52ee3/v3/graphql"
          NEXT_PUBLIC_TAKESHAPE_ANONYMOUS_API_KEY: "a9a84ace044c4d2796112c5710008a2f"
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_51JG7sTEjMGaPiQ74KqSiOjmOM3A64zrSHkogtR9rzMfC3PZauNAwGV7nDZmH1tNx9LwcJT7pLoKwMZSHaW30EifX00dYuNHWaq"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: artifacts-${{ github.run_id }}
          path: |
            ${{ github.workspace }}/cypress/screenshots
            ${{ github.workspace }}/cypress/videos
